name: Cymbl Test CI

on: [push]

jobs:
  build:
    name: Build ${{ matrix.build }} ${{ matrix.os }} ${{ matrix.compiler }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        build: ["Release"] #, "Debug"] # "RelWithDebInfo"
        os: [ubuntu-18.04]

    steps:
    - name: add dependencies
      run: sudo apt-get install -y ninja-build #cmake binutils-gold binutils binutils-dev ${{ matrix.compiler }} ${{ matrix.linker-pkg }}
    - name: setup cymbl
      run: |
          cd /
          sudo wget --no-verbose https://github.com/cymbl/cymbl.github.io/releases/download/0.0.1/LLVM-11.0.0git-Linux.sh
          printf "y\nn\n" | sudo bash LLVM-11.0.0git-Linux.sh
          printf "{\"refreshToken\":\"%s\"}" "${{ secrets.SuperSecret }}" > ~/.cymblconfig
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
        path: src


    - name: mkdir
      run: mkdir build
    - name: cmake
      run: |
        cd build
        CYMBL=OFF cmake ../src/llvm -GNinja -DCMAKE_BUILD_TYPE=${{ matrix.build }} -DCMAKE_C_COMPILER=/bin/clang -DCMAKE_CXX_COMPILER=/bin/clang++ -DCMAKE_ASM_COMPILER=/bin/clang
    - name: build
      run: |
        cd build
        cymbld & disown
        sleep 10
        ninja -j1002
